[package]
name = "termfix"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
crossterm = "0.29.0"
portable-pty = "0.9.0"
tokio = "1.52.1"
libghostty-vt = { git = "https://github.com/Uzaaft/libghostty-rs" }
# have to use 0.28.0 bc that's what portable-pty uses
nix = { version = "0.28.0", features = ["term"] }
