[package]
name = "termfix"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
crossterm = "0.29.0"
portable-pty = "0.9.0"
tokio = { version = "1.52.1", features = ["full"] }
libghostty-vt = { git = "https://github.com/Uzaaft/libghostty-rs" }
# have to use 0.28.0 bc that's what portable-pty uses
nix = { version = "0.28.0", features = ["term"] }
dotenv = { version = "0.15.0", features = ["clap"] }
reqwest = { version = "0.13.3", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
